name: petappgroup
description: "A pet care application with reminders"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.1.1
  timezone: ^0.9.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.8        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/blackcat.png
    - lib/assets/whitecat.png
    - lib/assets/browncat.png
    - lib/assets/orangecat.png
    - lib/assets/greycat.png

  uses-material-design: true